* manual/key

When busie at my Book I was upon a certain Night,
This Vision here exprest appear'd unto my dimmed sight:
A Toad full Ruddy I saw, did drink the juice of Grapes so fast,
Till over-charged with the broth, his Bowels all to brast:
And after that, from poyson'd Bulk he cast his Venom fell,
For Grief and Pain whereof his Members all began to swell;
With drops of Poysoned sweat approaching thus his secret Den,
His Cave with blasts of fumous Air he all bewhited then:
And from the which in space a Golden Humour did ensue,
Whose falling drops from high did stain the soyl with ruddy hue.
And when his Corps the force of vital breath began to lack,
This dying Toad became forthwith like Coal for colour Black:
Thus drowned in his proper veins of poysoned flood;
For term of Eighty days and Four he rotting stood
By Tryal then this Venom to expel I did desire;
For which I did commit his Carkass to a gentle Fire:
Which done, a Wonder to the sight, but more to be rehearst;
The Toad with Colours rare through every side was pierc'd;
And White appear'd when all the sundry hews were past:
Which after being tincted Ruddy, for evermore did last.
Then of the Venom handled thus a Medicine I did make;
Which Venom kills, and saveth such as Venom chance to take:
Glory be to him the granter of such secret ways,
Dominion, and Honour both, with Worship, and with Praise.
Amen.

[George Ripley. The Vision]
