* notes/phrases

- a flip flop is both memory and switch, swithcing back to oscillation to envelope and to change
- the gate is a gatekeeper
- self switching is the latch which is memory, positive feedback

* 3/7

clock as central - noise as clock, clock comparatored with noise,
shift reg clock, squared up noise as clock

clock as pulses

clock -> shift reg // filter // comp // as noise

all colours as pulse/noise/filter

ripley scroll

* 10/7

Shift reg/mostly in software:

https://www.embeddedrelated.com/showarticle/1112.php

https://www.avrfreaks.net/forum/256-bit-shift-register-required?page=all

http://electro-music.com/forum/topic-23881.html

* 19/7

- switch to MAX7490 - switched cap all purpose 2nd order x2 (so we can cascade
  for 4th order as compared to 8th order for MAX7400):

https://www.mouser.de/datasheet/2/256/MAX7490-MAX7491-91768.pdf

+5v, ext clock 100:1, QSOP16, 

- flip flop for shift register - flips on each clock/pulse

- shift register from http://www.cgs.synth.net/modules/cgs13v2_gated_comparator.html works well

16 shifted outs for clock OUTS in circle around

XOR also/ INS all buffered for fingers - TESTED

- to start adding to a test circuit...

* 26/7

- finger tested - op amp/buffer --|>---[] []---|>comp]=- (comparator with diode and 100k to GND)

- comparator also with finger voltage divider...

- question of AVR and/or shift reg/XOR etc. - but we need multiple ins
  and outs for AVR so maybe better served with ARM or with ATMEGA128

- TEST: how fast we can run shift reg, speeds and settings for various PWM

* 30/7

- manual in the form of a poster

- all digital sections (7490, AVR and even between both CLOCK) as blackboxed for 12v in and out = protection/ins and/or shift levels, CV in also

pulse inputs:
https://electronics.stackexchange.com/questions/43498/how-can-i-use-a-12-v-input-on-a-digital-arduino-pin
zener and resistor also as in microbd/SIR

pulse out as 2n2222, pulse in as transistor now

avr is 5v currently

- timing - for SR included code and simple pulse on/off is 130 KHz, fastest we can go with no code is 480 KHz

* 10/8

- have 16 pulse ins and outs and configure length of SR in software (maybe add one extra cv)

* 21/8

- have 7490 for bandpass or highpass and 7400 for lowpass (as is 8th stage and easier)
- gating of noise as pulses with primitive envelope/VCA with single transistor:

http://www.electro-music.com/forum/topic-33190-25.html

* 23/8

- maybe 7 ins/outs for pulses to micro, 7 envelopes-7 env is too many?

* 29/9

- see new ouroboros design as centre piece - perhaps exposed gold all
- check comparator out voltage and if we need to mix with micro/pwm for filter clock in
- new design follows eagle/worm/toad/earth
- earth as ripples in ripley sea
- LFSR as outer ouroboros
- check all possible signal paths for fingers and patchables
- standalone - fingers only with one input and out, euro - patchable internally and externally
- Q of switch for filter input between noise and other source (hand) 4066, 4053 - now dg419

* 29/11

- set 7490 as high pass and spec resistors - 10K for R2 and R4 and 200K for R3
- how to resolve finger/filter clock routings? - with another analogue switch // dg419

- list all jacks: *check this*

filter: in, clock in, lpoutx3, hpoutx3 [for feedback]

AVR/LFSR: cv_in, cv_in, clock pulse in, pulse in, pulse out, hf pulse out, hf pulse in

noise: 2x noise out for patchings, comp1, comp2, compout for processing

ouroboros: in and out

envelopes? - maybe leave as fingers only or one envelope in, in2, out

/////

- what is size in HP (for standalone we could use 4ms pod as 26, 32 or 60 HP - also frap tools)= *32HP=162.5mm* or 42HP?=213mm

(height 128.5)

- how many pulse in/outs from atmega 6in 6out 2env? 6 ouroboros...

pulse in and out low and high frequency versions??? where to place?

6x pulse in/out low +1 pulse in HF, +1 pulse out HF

- sketch analogue only version for larger home etch... - fingers and two jacks...
- how to connect top and bottom pcb - jack height = 11mm (smd options for top panel?), how many connections 

eg reich: SL 2X36G SMD2,54 on one side and 8.5mm on the other

- comparator on one noise source

- normal signal path noise->comp->filter/pwm clock on filter->LP/HP OUT

- check comp as usual/flat gives straight noise out - which it would never do so we need to make this modular/seperate

* 30/11

- decision to make all patchable by jack and finger. so no switches/dg419, no norms
- thus we need to work out common patches so we can have all jacks

layers: 

filter
avr/LFSR/pulses
noise-ouroboros-osc

where we put comparator/env/low and high freq sections?

comparator=gatekeeper/triangle

- lose filter comp as we have comparator as modular, lose also avr comp for clock (replaced with pulse in)

- maybe add extra modular comp

* 4/12 ++  19/12

TODO:

- +check footprints for both projects...+
- misc graphical elements and overlays...
- noise as drops for analogue/etc
- flip-flops/toggle analogue switches (for touch open analogue version):

flip flops: 4013, 7474, 7473

dg419 or 4066/4053 or even transistor switch (as in rough envelope but then we have one way only - but we can use for other audio paths)

the simplest thing to do is to AC couple the in/out pins and bias them
to the middle of the 4053's power supply. In a +9V system, this only
needs a two resistor divider and a cap, then a resistor and capacitor
per in/out pin.

what are paths to switch

circles/layers:
1-exposed comparator
2-ouroboros
3-switched noise
4-SR
5-filter (paths in?) 

- test 7490 as bandpass again with noise source
- question of mhz for pwm -> test

- *place low pass on output in case pwm comes through*

- for analogue only: flipflops for shift register so we have access to
  all ins (which are also outs but guess simpler/unbuffered), delay
  (switchable) on ouroboros - cap to gns

- question of bias for ouroboros...

TEST: flipflop touch switch and SR, bias on ouroboros. delay on ouroboros

refs:

http://mickeydelp.com/blog/anatomy-of-a-drum-machine?

http://www.sdiy.org/richardc64/new_drums/dr110/dr110a1.html

transistor comparator: http://ch00ftech.com/2012/06/20/2279/

question of abstracting out connections and elements. eg. clocks, different clock sources and should we divide these?

* 3/1 design notes

- panel breakout for euro/less analogue version: replace pads, *how many?*, include voltages and in/out - interchangeable front panels hand-made perhaps
- hand drawn transistor ouroboros in centre
- led triggered by micro in middle underneath exposed/no soldermask portion (how to expose all?)

* 7/1 tests:

- 1M on ouroboros makes things quieter and more stable - we could use finger pads for bias up and down

- TODO/TEST:

- test sr cell idea(?) from philips pdf
- capacitor delay on ouroboros - say 1n between collector and base (noisier but need to see how it works properly)...

// for simple All Colours

+- pwm mhz changes DONE+

+- 7490 bandpass with noise sourceDONE+

- flip/flop touch 4013

- in out transistor micro pulses and inv/non-inv amps for finger ins? (buffers on first straight followers)

OUT - lose pull down and reduce collector to 1k, base is 10k - at highest freqency we lose gain (MHz)

IN - could reduce base resistor (47k) but seems to work ok with buffered signals, test more, and no pulldown, and with hc14?

- offsetted clocks with logical operations across clock rings - SR is
  NOT pulses (we could AND it with its clock), but out of micro SR
  simulation IS pulses

- different smd transistors tested for noise generators and re-check BEC layout etc...

* 29/1 from touch: analogue/breakup tests

- only so many fingers, so use more flipflopped paths as a way of patching
- audio in/out path should not use fingers
- test individual circuits and keep simple ones as insignias...
- pads too small and too close to gnd/other signals
- for ouroboros we need switching in/out to avoid oscillation
- check transistor layouts!

* 7/2

- what we could do for test SMD assembly/quote - STM, base board or front panel with ouroboros and other simple circuits...

* 12/2

- ALL pulses/SR are in interrupts, all as multiple pulse outs without modes/cases for these, modes only for how SR connects and for slower SR stuff

- open and close ouroboros in one place with both touch flipflops and finger/transistor in

- spiral out from ouroboros with switch/latch/env elements/recursive/noise

* 20/3

- add extra 7490 in chain for extra poles
- add 4 or 8 bit DAC on shift register/AVR

* notes

- ignore other all_colours schematics in ERD!
- copy and add to git so can change schematic - DONE

- add one shot flip flop. monoflop/uniflop from DDR book - where we put this or
  could be in atmega? - makes pulses of uniform length before 7400?
  and after comparator

monoflop=monostable multivibrator?

- Henry noise seems to be low for input into 7400/test
- external clock for 7400 only works with comparator/noise not external signal
- test inputs to 7400

  - add clock input diode limiters DONE added on proto
  - add maxim 7400 input limiters using tl071 DONE
  - is Sample/HOld working? - try reverse GSD to DSG for our 2N5457 and try remove R20 - maybe needs re-design for right parts and slew NOT USED
  - how to deal with multiple switching paths for feedback JACKS
  - shift register in feedback path? ATMEGA
  - further elaboration with hand/finger/capacitive sensing mandala? - changing high freq clock with hand/fingers?

* key 

sockets from left into pins 

sockets: 2143 ???why???

pins: 00001234

CO  comp out
BI  buffer in
BO  buffer out
BI  buffer in
BO  buffer out
SHI samp/hold in
SHO samp/hold out
SHC samp/hold clock

COC comp cv
COI comp in
HNO henry noise out
YNO yusynth noise out
74O 7400 out
74C 7400 clock
74I 7400 in
G   GND

* atmega software

length of SR 16-32? - 16=65,535

- pwm out for maxim 100x, pulses out from SR, SR and CV to pwm, primitive DAC out, modes
- CV in for SR, pulse in for lock and random leakage, knob for modes, slew knlob and cv in
- SR code and leakage, lock/unlock
