* 3/7

clock as central - noise as clock, clock comparatored with noise,
shift reg clock, squared up noise as clock

clock as pulses

clock -> shift reg // filter // comp // as noise

all colours as pulse/noise/filter

ripley scroll

* 10/7

Shift reg/mostly in software:

https://www.embeddedrelated.com/showarticle/1112.php

https://www.avrfreaks.net/forum/256-bit-shift-register-required?page=all

http://electro-music.com/forum/topic-23881.html

* 19/7

- switch to MAX7490 - switched cap all purpose 2nd order x2 (so we can cascade
  for 4th order as compared to 8th order for MAX7400):

https://www.mouser.de/datasheet/2/256/MAX7490-MAX7491-91768.pdf

+5v, ext clock 100:1, QSOP16, 

- flip flop for shift register - flips on each clock/pulse

- shift register from http://www.cgs.synth.net/modules/cgs13v2_gated_comparator.html works well

16 shifted outs for clock OUTS in circle around

XOR also/ INS all buffered for fingers - TESTED

- to start adding to a test circuit...

* 26/7

- finger tested - op amp/buffer --|>---[] []---|>comp]=- (comparator with diode and 100k to GND)

- comparator also with finger voltage divider...

- question of AVR and/or shift reg/XOR etc. - but we need multiple ins
  and outs for AVR so maybe better served with ARM or with ATMEGA128

- TEST: how fast we can run shift reg, speeds and settings for various PWM

* 30/7

- manual in the form of a poster

- all digital sections (7490, AVR and even between both CLOCK) as blackboxed for 12v in and out = protection/ins and/or shift levels, CV in also

pulse inputs:
https://electronics.stackexchange.com/questions/43498/how-can-i-use-a-12-v-input-on-a-digital-arduino-pin
zener and resistor also as in microbd/SIR

pulse out as 2n2222, pulse in as transistor now

avr is 5v currently

- timing - for SR included code and simple pulse on/off is 130 KHz, fastest we can go with no code is 480 KHz

* 10/8

- have 16 pulse ins and outs and configure length of SR in software (maybe add one extra cv)

* 21/8

- have 7490 for bandpass or highpass and 7400 for lowpass (as is 8th stage and easier)
- gating of noise as pulses with primitive envelope/VCA with single transistor:

http://www.electro-music.com/forum/topic-33190-25.html

* 23/8

- maybe 7 ins/outs for pulses to micro, 7 envelopes-7 env is too many?

* 29/9

- see new ouroboros design as centre piece - perhaps exposed gold all
- check comparator out voltage and if we need to mix with micro/pwm for filter clock in
- new design follows eagle/worm/toad/earth
- earth as ripples in ripley sea
- LFSR as outer ouroboros
- check all possible signal paths for fingers and patchables
- standalone - fingers only with one input and out, euro - patchable internally and externally
- Q of switch for filter input between noise and other source (hand) 4066, 4053 - now dg419

* 29/11

- set 7490 as high pass and spec resistors - 10K for R2 and R4 and 200K for R3
- how to resolve finger/filter clock routings? - with another analogue switch // dg419

- list all jacks: *check this*

filter: in, clock in, comp1, comp2, lpoutx3, hpoutx3 [for feedback]

AVR/LFSR: cv_in, cv_in, comp1, comp2 for clock, pulses in, pulses out (how many?), hf pulse out, hf pulse in...

noise: 2x noise out for patchings, comparator in for one noise source

ouroboros: in and out

envelopes?

/////

- what is size in HP (for standalone we could use 4ms pod as 26, 32 or 60 HP - also frap tools)= *32HP=162.5mm* or 42HP?=213mm

(height 128.5)

- how many pulse in/outs from atmega 6in 6out 2env? 6 ouroboros...

pulse in and out low and high frequency versions??? where to place?

6x pulse in/out low +1 pulse in HF, +1 pulse out HF

- sketch analogue only version for larger home etch... - fingers and two jacks...
- how to connect top and bottom pcb - *check height of jacks*

- comparator on one noise source

- normal signal path noise->comp->filter/pwm clock on filter->LP/HP OUT

- *check comp as usual/flat gives straight noise out*

* 30/11
1
- decision to make all patchable by jack and finger. so no switches/dg419
- thus we need to work out common patches so we can have all jacks

* notes

- ignore other all_colours schematics in ERD!
- copy and add to git so can change schematic - DONE

- add one shot flip flop. monoflop/uniflop from DDR book - where we put this or
  could be in atmega? - makes pulses of uniform length before 7400?
  and after comparator

monoflop=monostable multivibrator?

- Henry noise seems to be low for input into 7400/test
- external clock for 7400 only works with comparator/noise not external signal
- test inputs to 7400

  - add clock input diode limiters DONE added on proto
  - add maxim 7400 input limiters using tl071 DONE
  - is Sample/HOld working? - try reverse GSD to DSG for our 2N5457 and try remove R20 - maybe needs re-design for right parts and slew NOT USED
  - how to deal with multiple switching paths for feedback JACKS
  - shift register in feedback path? ATMEGA
  - further elaboration with hand/finger/capacitive sensing mandala? - changing high freq clock with hand/fingers?

* key 

sockets from left into pins 

sockets: 2143 ???why???

pins: 00001234

CO  comp out
BI  buffer in
BO  buffer out
BI  buffer in
BO  buffer out
SHI samp/hold in
SHO samp/hold out
SHC samp/hold clock

COC comp cv
COI comp in
HNO henry noise out
YNO yusynth noise out
74O 7400 out
74C 7400 clock
74I 7400 in
G   GND

* atmega software

length of SR 16-32? - 16=65,535

- pwm out for maxim 100x, pulses out from SR, SR and CV to pwm, primitive DAC out, modes
- CV in for SR, pulse in for lock and random leakage, knob for modes, slew knlob and cv in
- SR code and leakage, lock/unlock
