* 3/7

clock as central - noise as clock, clock comparatored with noise,
shift reg clock, squared up noise as clock

clock as pulses

clock -> shift reg // filter // comp // as noise

all colours as pulse/noise/filter

ripley scroll

* 10/7

Shift reg/mostly in software:

https://www.embeddedrelated.com/showarticle/1112.php

https://www.avrfreaks.net/forum/256-bit-shift-register-required?page=all

http://electro-music.com/forum/topic-23881.html

* 19/7

- switch to MAX7490 - switched cap all purpose 2nd order x2 (so we can cascade
  for 4th order as compared to 8th order for MAX7400):

https://www.mouser.de/datasheet/2/256/MAX7490-MAX7491-91768.pdf

+5v, ext clock 100:1, QSOP16, 

- flip flop for shift register - flips on each clock/pulse

- shift register from http://www.cgs.synth.net/modules/cgs13v2_gated_comparator.html works well

16 shifted outs for clock OUTS in circle around

XOR also/ INS all buffered for fingers - TESTED

- to start adding to a test circuit...

* 26/7

- finger tested - op amp/buffer --|>---[] []---|>comp]=- (comparator with diode and 100k to GND)

- comparator also with finger voltage divider...

- question of AVR and/or shift reg/XOR etc. - but we need multiple ins
  and outs for AVR so maybe better served with ARM or with ATMEGA128

- TEST: how fast we can run shift reg, speeds and settings for various PWM

* 30/7

- manual in the form of a poster

- all digital sections (7490, AVR and even between both CLOCK) as blackboxed for 12v in and out = protection/ins and/or shift levels, CV in also

pulse inputs:
https://electronics.stackexchange.com/questions/43498/how-can-i-use-a-12-v-input-on-a-digital-arduino-pin
zener and resistor also as in microbd/SIR

pulse out as 2n2222, 

avr is 5v currently

- timing - for SR included code and simple pulse on/off is 130 KHz, fastest we can go with no code is 480 KHz

* notes

- ignore other all_colours schematics in ERD!
- copy and add to git so can change schematic - DONE

- add one shot flip flop. monoflop/uniflop from DDR book - where we put this or
  could be in atmega? - makes pulses of uniform length before 7400?
  and after comparator

monoflop=monostable multivibrator?

- Henry noise seems to be low for input into 7400/test
- external clock for 7400 only works with comparator/noise not external signal
- test inputs to 7400

  - add clock input diode limiters DONE added on proto
  - add maxim 7400 input limiters using tl071 DONE
  - is Sample/HOld working? - try reverse GSD to DSG for our 2N5457 and try remove R20 - maybe needs re-design for right parts and slew NOT USED
  - how to deal with multiple switching paths for feedback JACKS
  - shift register in feedback path? ATMEGA
  - further elaboration with hand/finger/capacitive sensing mandala? - changing high freq clock with hand/fingers?

* key 

sockets from left into pins 

sockets: 2143 ???why???

pins: 00001234

CO  comp out
BI  buffer in
BO  buffer out
BI  buffer in
BO  buffer out
SHI samp/hold in
SHO samp/hold out
SHC samp/hold clock

COC comp cv
COI comp in
HNO henry noise out
YNO yusynth noise out
74O 7400 out
74C 7400 clock
74I 7400 in
G   GND

* atmega software

length of SR 16-32? - 16=65,535

- pwm out for maxim 100x, pulses out from SR, SR and CV to pwm, primitive DAC out, modes
- CV in for SR, pulse in for lock and random leakage, knob for modes, slew knlob and cv in
- SR code and leakage, lock/unlock
