** description/manual

- video/manual (burnt manual card?)

*- fake trigger//how do we trigger for video... (code-in special delay just for video - say 5s - TESTMODE)*

// desc/for manual card/for website

Die Grausamkeit des ewigen Tods. Lucifer Antichrist und sein Mutter ein Leib und Sele: ist fix und volatile.

ERD/FUSE is the first eurorack module designed to trigger and initiate
pyrotechnic or explosive events from within the modular domain.

ERD/FUSE acts as a bridge between gate or control signals, and
multiple controlled ignition events. Under various operational modes,
trigger signals are used to ignite either electric matches (ematch) or
clip-on (talon) igniter in complex sequences.

ERD/FUSE can ignite up to four electric matches or clip-on igniters
whose cables are inserted into the module, using four trigger signals
in various combinations according to mode. Ignition can be selected to
last 100ms (electic match) or 2 seconds (talon).

Operation:

- Connect eurorack power with red stripe (-12v) towards the bottom of the module.
- Connect a 12v 2A (minimum) power supply (2.1mm jack, centre positive) to the power jack.
- Select a mode by rotating the mode knob. The selected mode is indicated by the binary display above the row of jacks.
- Plug the trigger signal into the selected trigger jack (1-4 left to right),
- Make sure the display LEDs do NOT flash. Clip the ematch or trigger cable copper ends into the relevant port matching the jack (1-4 top down). 

- At a safe distance from the modulor, attach the ematch to the pyrotechnic device to be triggered, following manufacturer's instructions.

- Arm the ERD/FUSE to fire the ematch according to trigger or mode by
  pressing down the mode select knob and releasing it. A quick press
  selects 100ms trigger, a press over one second selects 2 second
  trigger. The mode LEDs will now flash (fast or slow) to indicate
  that module and the devices are armed and ready. Do NOT approach the
  devices to be triggered until all devices have successfully fired,
  and the FUSE display has stopped flashing.

- According to mode and input signal, explosive events will be
  successively triggered. Once all events attached to all four
  triggers have been achieved, a new mode can be selected, a new set
  of triggers can be attached, and the module can be re-armed.

Modes:


Technical:

10HP, mA at 12v, 0mA at -12v. 4 gate/pulse/CV inputs (>4v trigger), 4 electric match/talon compatible output pairs. 

ERD/FUSE requires a 12-15V, 40W+ brick power supply with a centre positive
2.1mm DC jack plug (eg. MEAN WELL GST40A12 Desktop power supply). This
is not included. The power is plugged on the left side DC JACK.

** pyro module for 4 triggers

prog: HEADER from top: reset, MOSI, MISO, SCK, GND // BLACK at top (black, white)

10HP 50.5mm

- 4 pulse inputs DONE
- 4 sets of terminals for triggers (from FETs)
- switch on encoder arms the device
- how to show is armed - some display/LED/nicer? but cutout to show this/surface mount - or like 4 bright leds with slit// to test?
- UV light would be nice
- power socket as in breath - but widen the pins for segor socketDONE

specs now:

ematch: 1/10th second ignition 2A = 100 ms
talon (clip on igniter): 2 seconds

*what is voltage for input? 12V*

question of any delay after trigger: none!

+also if we can fire in series/parallel??!?? and how many+
+what of potential short at 2 seconds pulse???+

//DISPLAY we need to show:

- that is armed - flash. length of trigger - flash and gap length
- mode - 1-15 on 4 bits
- [show also state of incoming pulses... but confuses with flashing... could maybe invert them // and show when unarmed (but what of mode)]

** modes

- different modes eg. single trigger sets off all, at interval x... next on x does x... enables/etc, length of pulse out

eg.
TESTEDfine!
1- trigger sets off each oneXX
2- trigger on first sets off allXX

TEST:
3- trigger on first sets off first and then primes rest to set off on their own trigger 
4- pair arms or primes other - so one goes off after other 
5- in sequence but on trigger - so one sets 2 ready, 2 sets 3 and 3 sets 4 (ie. only 3 has fired can 4 go on its trigger, ignore before that)

TODO:
X- trigger within time window on all sets off all???  // different size of windows below 
X- same for pairs in window = sets on pairs // different size of windows below
X- trigger on first sets off each in series at successive interval of X, Y, Z(how that is determined?) 1-2-3-4

15X- no trigger just 10 seconds and fire all - last mode

sizes of windows: 1 second, 2, 4, 8, 16 = 6,7,8,9 + pairs 10,11,12,13

sizes of interval: 4, 8 = 14,15 or we measure interval...??? - prime on 1st, measure and fire 2nd and use time for next 2

X- trigger each one after x second delay...

set a delay of x Ms from now ???

TODO more modes ->15

** specs panel/base:

- Cliff FE6930 is socket/vertical

- size of pluggy cutout approx 28x50mm, for LEDs: 0.8mm x 40mm

** TODO:

- DONEreverse display count (check again) and eliminate the 0
- DONElength as length of press
- DONEflash display mode + length etc.
- DONEswitch all functionality now to interrupts - what was timing??? 100ms for short pulse... now we have 200Hz interrupt.. measured...

- implement and test all modes and timings

- video/manual (burnt manual card?)
- +25x order jlcpcb - +waiting for XTAL!-16MHZ++

** 26/8/2024
- added all new modes to be tested and refined
- document all new modes. test and fix on new mode/short trigger for THU!

** 23/8/2024

- pulled out ignition... TESTed and fixed bug in flashing code...
- *NOTE: that counter/case we add one to display as there is no zero*
- *NOTE: TODO: norm to GND, note our firstproto doesn't have the pulldowns.. fixed now and in production*

** 8/7/2024

- DONE:switch all functionality now to interrupts - what was timing??? 100ms for short pulse... so say 5 interrupt = 200Hz

[where was atmega interrupt code - in SIR was TIMER2 = 200Hz]

** 25/6/2024
- basic infrastructure implemented, tested though timing still to check... and TESTS of first 2 modes
- remaining modes TODO

** 29/2/2024

- panels arrived - use washers for jacks, and FINE:testing now gluing of panel to socket thing else pcb bends horribly (other option is screw into plastic!)

** 22/1/2024

- remember that      sbi(PORTD,0); is pin 0
- +unresponsive with 2s delay and primed - need to workaround that...+DONE///
- +shorting test: fine... try longer/ fine...+
- +fine with cable extension+
- +trial 4 all connected in parallel to one port+

** 4/1/2024

- +question of resistor (30W 6 ohm for short protection - but what is 65W and 3ohm of FET.+ FET is: IRLB8721PBF
- maybe have just 15 modes we rotate through and press defines length:

short or long press: 1/10th / 2 secs

** 12/10/2023

TODO:

- +test 4 triggers at same time - heat residue - how to measure?+
- +test 2 second short?+
- +NONdefine say 8 modes and 3 sets of timings+ - how many things on encoder?? 24 detents // checked

YES!or *we just turn round and round for X modes ... multed by timings*

- so say we have 15 modes: note: that we can't flash ZERO so gives 15 modes in any case to indicate

- flash mode on armed with times of ignition 

grey code //another encoding...?

//DISPLAY we need to show:

- that is armed - flash. length of trigger - flash and gap length
- mode - 1-15 on 4 bits
- [show also state of incoming pulses... but confuses with flashing... could maybe invert them // and show when unarmed (but what of mode)]

** 3/10/2023

- DONEtested e-match trigger (extend cables)
- added bounce cap and pull downs for trigger ins to schematic and PCB (100K)
- all tested just need to do logic, modes, check timing and heat

Idea is to have 15 modes which can be displayed and then cycle these
for longer ignition time (we could flash armed at different speeds to
show this timing...)
 
- TODO: explain front panel to ilyas: cutout for LEDs (very thin slit - 0.8mm), cutout for socket thing, [own: what graphics if any]???

size of power jack: 8.1mm thru hole, 8.6mm pad

** 2/10/2023

- revisit:

-DONEneed to test trigger outs - hookup LED
-armed will always flash mode lights then flash triggered device when goes off

DONE:
- pulseins tested 
- encoder ported (switch changed C10 to pulldown) - DONE:to update on PCB*
- LEDs working
- tested trigger outs with LED on all

** 16/xx/2023

- starting to test HW and work on software

- test basics: programming (fuses) using pololu, makefile, basic code DONE

code to test: flash LEDsDONE, read from inputs, trigger outs, read from encoder

HEADER from top: reset, MOSI, MISO, SCK, GND

black/reset, white, black, brown, orange (and connect own power/bus pololu)

** started july 20

- schematic started
- tested encoder: PEC11R-4215F-S0024

- sizes and selection for clamps?

** desc for pcbman

I have a new design for you - it's for a eurorack pyrotechnical
ignition module! Here are the details below, if there's anything I've
missed let me know. Attaching kicad zip and a rough layout.

Base PCB (106x50mm) and 10HP panel (128.5x50.5mm) with:

- 4 jacks as usual
- Cliff FE6930 clip thing with terminals in base PCB so it can be
  mounted/soldered in place there and pokes through a cutout on the
  panel pcb - check datasheet. On the schematic it is just an 8pin connector. I left it free in the footprint association/netlist.
- 4 SMD LEDs (0805) across the width of the base which are viewed through a very narrow slit or unmasked area (1mm) in the top panel (marked in black)
- Rotary encoder: PEC11R-4215F-S0024 footprint? I left it free in the footprint association/netlist.
- PCB zone heatsink under each FET on the PCB!
- All parts can be on the back of PCB

If you can design a not-so-precise base PCB (without panel) so I can test this first without the top panel that would be great!
