* schematic


TESTS:

- basic binticDONE
- expanded with signum

== see below// is signum working? // is bin3 working (how to test on own as all have feedback)

all bin 1 2 3 seem to work in same way so...
fixed 2.2k on r99 4th vca as was wrong part

vpp is around 20v (too high) - why so high? - signum maybe sends over so keep lower vca? some tweaks...


- Mindlin
- crossover

** 12/5/2022

- extend with extra integrator/bintic and signum neg into signum but
  we don't have spare VCA so just use pot/inv (not inv4)// also hard to know where to extend from....

tried from out of 2nd integrator/not neg -> bb3 then r1 into signum and back into first integrator - 

mindlin: 
R1 highest - C3 x
R2 lowest - C1
R3 mid - C2 x
r1 and r3 were mults

and C4 is first R

** 10/5/2022

- either dual/split or switching (then need to find good switch) or some hybrid of this
2 branches join...

*first Mindlin notes:*

- setup as book but 1st R between integrators works well at 100ohm (tried 1k.10k then is more like sprott ringing)

- can also be VCA (noninv)

- try: replace invertors with VCA inv (to test)DONE... +on one it only works with one of the invertors??? (inv4) which is the one we turned into integrator! [but with that extra integrator+

- simplifying... we can remove B(t) multiplier and just use VCA, same for E(t) or vice versa

- q scaling of these ins and also of VCA vs mult (see above - both do similar job)

+r2 doesn't do much,,,but...+

** 9/5/2022

- thinking about split/combine of mindlin/sprott - that can be just 2 sides rather than doubled up, and with norms across one to other
or switches of paths one to other...
- also norm of sprott out back to its own clock
- investigate other outs: B1x, B2x, B3x, R1 (we use)

- now patch mindlin: nada at first (also norm q for 2 inputs), multiplier always hot: *ad633 ar soic has different pins to what we have on pcb...*

+where are DIP for testings?+

- think of smaller utilities eg. onebit/sigmadelta

** 6/5/2022

analogue thing: 

- *for G(x)= -B(x) + Csgn(x) // which is just with inverter before the G(x) so is what we had below with last VCA inverted!*

but we have adjustable ratio within the signum...

from sprott (a new class): B=1.2, C=2.0

1/1.2 for signal = 8.333k vs 1k ref
Vs/C = 10/2 = 50k for signum

but on coeff6: signum = same more or less as signal: try with own circuit (and scope?): r68 (leave as 2M)

** 5/5/2022

- signum trials with analogue thing:

implemented with comparator and with no input we have chaos with exact
equation/layout but with very precise settings for signum relationship!

also very low freq but now add inbetween coeffs - still low and unstable 

coeff5 is signum amount
coeff6 is siganl in Cx-bsgnX


- trial last integrator is not switched - change last INV4 (r90) to 10n integrator and ditch r89:

again nothing when have last VCA non-inverted....// and double checked vca4 is all fine

- under what conditions it stops (as is just extra feedback?)

Q if is inversion before b3 which counts or??? as long as there is inversion (so can also be after signum)
try sans signum(still inversion issue)

*stability of signum with no gnd bias on comparator?* - how to re-test this 

- maybe ditch signum so is just bintic merge with mindlin // bintic vs. mindlin...

** 4/5/2022

- fixed up all VCAs with new values (not think on CV in now) 

- test BINTIC [d1=dd1 inv], rest +

bintic is fine, but still SIGNUM thing on positive vca (so minus back in) just bumps down/up to rails...

** 3/5/2022

- according to equations last/3rd/signum path should not be inverting ????

X''' = -G(x) + Ax'' + x'

- 100k also in last path is necessary (we have 22k in R72 already but up to 100K)

- worried about impedance in LM13700 inputs - how can we change this - LM13700 is fine but prob in current control

also 1k in bintics to check and 100k for gnd on damper to maybe add...

Iabc is control current max 2mA // recalculate

say for 1st R40 and R41 is 100K then r44 is 22k (we can also change top in pot/divider) - seems to work fine as is with changes noted

- temp remove r9 to test 1st invertor as is offset...// replaced

** 2/5/2022

- if we invert b3->bb3 (so input to 3rd integral - x which goes to
  signum) then seems stable and quite interesting 

** 29/4/2022

r68 try 1.5m according to calcs for 12v // try 2m as no 1.5 -- trying but still unstable

** 28/4/2022

- revisiting - had to resolder u1 1st amp does have connection to b3 through r9 which explains what we thought was bleed

////
- +basic bintic with 2x switched caps and 3x vca is strong on clock and not much input+ - was one cap unsoldered now fixed and behaves well...
- bit now with 3x bintic/integrators and signum is 10v no signal out from R1->out amplifier

signals from others... is bb3 bin/int working??? fixed r24 and worked a bit/not now//signum?

d1 to dd1 is inverted...

- how did we calc values for VCAs - halving signal at max?

** 22/12/2021

- if we think of a simple switching analogue comp - with several 4066
  switch points which can be switched by hand (a switch, touch/toggle)
  or by CV->comparator

what voltage can 4066 handle/what is its max power? as on touch toggle
we use +-9v to power - i think is 18v so we need to design around this

** 19/10/2021

TOAD test/configurations: bottom ad633 needs replacing,
sigma-delta-comparator is wrong way round for data return so only
works with invQ - but why doesn’t work with high freq AC signal - as
need to raise gnd from clk comparator as in bintic comp...  bintic to
test still, vca to test fully-works

- we change r68 for x-signum(x) as the signum is very high (-12 to +12v) so we have 1M for the moment and looks better

- we need to test bintic with VCA

sort of works in odd ways but ok with simple set up with 2x switched caps and damping in signum/or inversion

TODO from above/notes: swop sigma-delt comp +- for data return, fix clock comparator in there/test on breadboard maybe

** //////

In progress - from previous filter design but now merge of SIGNUM
chaos, WASP 4069 filter with extra integrator, and bintic switched
cap filter:

To note for new schematic:

- +12v and GND only throughout except first and last stage
- maybe add OTA/VCA on input too
- OTA control of b1/bb1 - b2/bb2 and b3/bb3 is all from same CV - one knob/cv

- OTA control of VCA in, damping?? and SIGNUM feedback is all CV - so 2 or 3 more knob/CV

- all 4069 are seperate to avoid heating - do we need to GND extra pins? no

- TEST: WASP feedback with diodes ->

- On breadboard is from where damping would be //2nd stage// - we just have 100k and
  pot at moment - test with wasp feedback - tested and works well but
  we can't put under voltage control

- Original damping option with 22k (or otherwise) to GND and OTA
  feedback (on sprott that was inverting then into inverting in so we
  test it non-inverting ??) TEST

- test LM13700 with extra op-amp (we tried this for first stage B1/BB1 and seems to work but then we need to go inv and inv - TEST for all


- prototype PCB with all stages pluggable, NLC-style SIGNUM also patchable and invert/non-inv input options for each OTA  

- note that in HAIBLE/DUAL WASP there is 1k in parallel with 10k LIN pot and 1k and diode at bottom of pot - this is to turn into log pot?

- in sprott what we have for last SIGNUM feedback stage is x-signum(x) which is same as in Sprott paper "A new class of chaotic circuit"

G(x)=Bx-Csgn(x) which plugs into x``` + Ax`` + x` = G(x)

x``` + Ax`` + x` = Bx-Csgn(x)

so: x``` + Ax`` + x` - [Bx-Csgn(x)] = 0

which is close to:

sprott manual is ax``` + bx`` + [cSGN(x) - dx] = 0

where is x` ??? 

* TODO

- front vca or not? TESTED and gets complicated...

so we have 3 mid stages controlled by one CV, damping-CV, SIGNUM CV = 3xCV so maybe


- 47k for ota stages

- test different feedback options for damping/first feedback loop:
  tested 51k to GND and straight 13700 through (+) and this works
  fine: maybe leave WASP feedback as an option on test pcb

- test all feedthrough 13700 with extra op amp and inv/inv setup - so 2 extra to do - seems to work out also but values will need to be tweaked

- test extra op-amp on signum but then we reverse the OTA! - tested but not sure - so leave as is...

- maybe leave out alt signum
