* see also software/modes.org

** 20/4/2023

- that after freeze we can still add value to freeze as a
  baseline. makes sense for VCA (and voltage). otherwise the pad does
  nothing and can always be left alone. To make sure all modes make
  sense, even if not sure which mode one is in...

** 29/3/2023 TODO:

- start to define tasks from below:

-basic functioning: what is prescalar, how long do we want top record for, what is frequency resolution, any artefacts, speed up and slow donw
-define timings and check all mode/freezes etc.
-define and implement modes
-BOM, assembly...

- use debug to figure out rough rec speed? every 6 or so seconds // prescalar of 8

with prescalar of 32 we have 22 seconds (so not quite with out calculations)

*which prescalar?*

- test logspeed and speed modifiers (speed starts from slowest?)

** 27/3/2023: REVISIT2

TODO:
- re-check basic functioning
- HW and washers - as we don't seem to use them: tested now with one washer and is fine..., BOM/update any footprints (what are ones for assembly:

Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm

SM1206POL

which is correct base PCB - last one?

- re-acquaint code - how well it works as basic and calibrate speed again...
- list of new modes to do in new_modes.org - check older code, modes lists

it_strip.c

- how to make sense? eg. speed ranges-logspeed, 1/8 speed, top bits ???

- top bits are used in modes in it.c for individual speeds
- range is logspeed - check this, 1/8 as we run through 8 DACs
  sequentially..., top bits were reserved for individual speeds...

- how fast does it run and  how many seconds of gestures by default???

7000 values in each array: 2kHz we say (at 32 pre-scaler to check as was last at 8): and there are 8 sections so each runs at 2k/8=250Hz

7000/250=28 seconds... TO CHECK!

** 4/10/2022

- *also do we have functionality to change speed of recording - so jumps/blends=interpolates like a slur of values...*

** 20/7/2022: REVISIT

- test what is working: basic functions, freezers, rec/play but is 1/8 speed correct - re-test as 1.0

- where are we up to with speed ranges - we have logspeed

- check/test code for mode switch and re-acquaint code: top bits to implement, basic schemes

- what modes still need to be implemented: list these - see modes.org for list there and older code...

** xxx

30/12/2021:

- switched over to HSE in system_stm32 rather than other clock init and seems to work fine but will need to recalibrate timings/re-check but freeze works

20/12/2021:

// so we might need to tweak the speed array but bleed is now SORTED!

- so no bleed with freezers as these don't involve the adc - what about on additive playback?TESTED fine 

- DONE:but we need to re-do speed as was for old adc scheme

17/12/2021:

SOLVED with single ADCs and lookup arrays.. 

- remaining bleed is in ADC array ... 

- note that 0 should be 16mV but we have 88mV with << scheme and single ADC

single ADC reduced bleed with <<2 to 88->112mV which is 24mV

single ADC fails to read case 2 channel 5???!!! - FIXED with disabling DAC channel 2

still slight bleed - lookup for values so we keep bottom low (try log too)

16/12/2021:

- speed code is re-written also now with logspeed to try out...

TODO: trial with all caps replaced for bleedthrough etc - 1NF DONE

still bleedthrough but is that anything to do with caps... (see how small we can go with c9 - 100pF?)

TODO:

different fingers for vca, 

also if we can change vca so opens a bit more: values there R52 was adjusted from 47k to 10K maybe trial other values

20k now we have and seems ok

15/12/2021:

- need to add overlap flag for rec and playback...DONE

- problems with speeds and aliasing so need to rewrite code without 32 steps

- try without the 32x slowdown for record (and speed will skip samples)

so we need 8x say upwards of 1KHz which is 8KHz in main loop

we have:

  // 1024/4 is 8x 862Hz (toggle speed so 2x that which is fine for us but we need to lower the sample/hold cap...

replaced c9 with 1NF (from 47NF)

1.6k=4 seconds..

14/12/2021 

- CV out peaks at 6v - 6.6v is our maxium for 4095

- VCA 4.24 VPP for 5v signal (4.6v is 4095 as I guess we close the VCA a bit) but we can only get to 4.2v on first VCA

- aliasing always - we need to re-think all speeds as DAC can only run up to 100 Hz

/// reduce capacitor in sample/hold from 47nF


+input filter is 15nF and 15k so gives cutoff of 700Hz x2=1.4KHz which is fine+

but rec is 32 times slower and each dac is x8 so that is 32x8=256

in theory is then 8KHz / 256 = 31Hz so aliasing

- so we make everything run faster but really need to resolve all and be very precise of speeds (filters in recording)

- what do we need to get to 1KHz - 256KHz clock

what is max recording again? if say we record at 1 KHz - 7000 samples is 7 seconds...

// need to check we run fast enough for that clock, alternative would be to software filter for recordings
