* notes towards manual/caput draconis

** basic blurb description: 

Caput draconis (CD) is/will be the latest ourorack ... companion

to have done with the judgement of god

successive pleasurable and tortuous dislocations 

//Successive Slidings of Pleasure (French: Glissements progressifs du plaisir) RG

extends the pulse driven shift register schemes of All
Colours with 4 and more interlocking shift registers or "runglers"
(each with 64 modes of operation) running at all different speeds. The
emphasis is on complex CV generation and processing of analogue
signals, as well as clock and pulse outputs. Release date March 2023.

[All the Colours of the Noise is a new rosarium of eurorack module for
ouroboric becoming-noise at all timescales and frequencies, from the
cloudy smoke of stray industrial furnace noise burning snakes to
thunder and lightning noise from stricken server farms.]


Closer to caput draconis as the crescent moon moves into the northern ecliptic hemisphere at 18.56 GMT this evening. 

Successive pleasurable and tortuous dislocations 

** design/inspirations

- collect stack/SR diagrams, ascii art, panel sketches, moon phases
- print quality and binding?

how to image/notate panel - that the description and panel/images are themselves subjected to shift reg (eg. each pixel line of panel image - try this!)


** 24/2/2023

announce moon node at 19.58!

As the crescent ...

images: new panelSr, inspired alch, moon diagram, geomantic

- image trial for panel - use forhyyt python to pass through 1-4 SRs (in test.c?)

with add functions but do basic test:

image -> string

C or python code manipulates string...

string -> image (and colour)

- thinking that manual could be A3 riso (but then folded?) poster... or set of cards like AC (for all?)

** 23/2/2023

notebook notes:

moon nodes and diagrams, connection to geomancy, ascii thurneysser

ascend/descend, digital moon

layout diagram of connected segments, show that can be shifting like turing reader drawings (and to do own reader)

layers - speed, route, prob, types

each side has...

modes...

** 20/2/2023

tips such as use of pulse ins if sections start to run out, also to mix in signals...

Computers for the Arts - Higgins, Dick as model with printed printouts/permutations, permutate our own instructions

the user shoots
the user kills

how to patch following geomantic instructions

** 9/2/2023

- how interacts with AC to fill in from notes:

- use of HF clock signals as strobe clock for CD
- use of comped noise as strobe and as noise/snare entry 
- feedback path with AC
- pulses from CD -> ?
- AC as audio source
- use of comparator for clocks

** new 4/5/2022+

- how to use with geomantic layout of 4 figures...

[from segmodes]
head fire C 1=one dot/active. 0=2 dots/passive. 
neck air L
body water N
feet earth R

each figure has active/passive lines (passive as static) for 4 layers - in the 4 elements

so then one card would give how to operate (eg. which to leave static) but then for 4 cards?

- grid of features with symbols eg.

      clk spd 
xmode  *   -

eg. does it use clk (as param, as timing/speed, as pulse)

what else??? fill in

also like grid from moods modes/

** Heavens material

https://academic.oup.com/jcmc/article/3/3/JCMC334/4584381

vehicle

 A walk-in can be defined as "an entity who occupies a body that has been vacated by its original soul"

next level

** or caput draconis materials

geomancy figures 

** ascii art/outputs for different SR varieties

** artful description/older

Heavens\ extends the pulse driven shift register schemes of All
Colours with 4 and more interlocking shift registers or "runglers"
(each with 64 modes of operation) running at all different speeds. The
emphasis is on complex CV generation and processing of analogue
signals, as well as clock and pulse outputs. Release date March 2023.

** basic description

how we call SR: as rungler, as a walk-in

Heavens\ presents four interlocking or overlapping shift registers, runglers or digital walk-ins.

Each register has a speed, a mode (of 64) and a length (up to 32 cells) which
can be varied in most cases by control voltage (CV), or by other
parameters. Each has a clock pulse input which, depending on mode
determines speed of the register or some other parameter, such as a
freeze or a strobe.

Each register has 64 modes which can only be selected by the mode
knob. There are 3 major modes which choose how the speed of the
register is determined: by speed CV, by speed CV and another shift
register, or by incoming clock pulses.

The top register is for incoming signals, such as the analogue input
or internal digital noise. Here the mode largely determines the type
of input and how it is processed (eg. how many bits).

The lowest register is for outgoing CV and audio rate signals which
are converted from the digital registers according to various schemes
set by the mode (eg. how many bits).

The left and right registers are used to delay, process and feed back
between top and bottom. The routing of the four distinct registers is
largely fixed as follows (again a few modes can change this fixed
routing). Top register feeds into left which feeds into both lower and
right. The right feeds back in to the top. 

Left and right registers have additional pulse in inputs and two pulse
outs. One of these is half the speed of the other/one division. The
lower register also has two pulses outs giving a total of six pulse
outputs and one analaogue CV/audio out.

All registers can run at differing speeds, the slowest speed is a full
stop which does not advance the register. If a register is running
faster than it's feed-in register it will cycle through a frozen copy
of that register (a ghost) which is updated as soon as the feed-in
runs again. This means that a stopped register will merely repeat its
contents feeding another faster or unstopped register. Some registers
further manipulate their own incoming ghost registers.

** modes drawn out - how we notate these eg. symbols for probabilty, how we make a grid?

** layout and panel scan

** other params/ power etc.

20HP, XmA at +12V, XmA at -12V, 0mA at 5v. Multiple inputs, single audio/CV outputs, multiple pulse outputs. Power is red stripe/-12V DOWN.

** any example patches

** links/reading list/reader

- other random
- http://www.ccru.net/digithype/Afrobinary.htm
- https://monoskop.org/images/f/f1/CCRU_Abstract_Culture_Digital_Hyperstition_1999.pdf
