* notes towards manual/caput draconis

** blurb 2

caput draconis is an ourorack (ouroboric eurorack) module for
gnarlular audio processing, and advanced serpentine all-frequency CV
and audio pattern generation, encoding a series of successively
pleasurable and tortuous sliding dislocations.

Four draconic heavily simulated shift registers are enchained,
interlocked, woven and segmented, recursively and excessively feeding
on each other in turns, vomiting noise and wormy symphonies according
to moon phases and shifting nodal and modal paths. It is to have done
with the judgement of god/s, snaking towards a synthesis without
modules.
 
With sixty-four modes per serpentine section, caput draconis is best
viewed as en-worming more than 16777216 (64^16) unique and complex
instruments, equally invoked and informed by lunar phases and
astrogeomantic time signatures.

** site/announce description - fill in

Technical and HOWTO
20HP, 110mA at +12V, 20mA at -12V, 0mA at 5v. Multiple CV/pulse inputs, pulse outs and 1 audio/CV output. Power is red stripe/-12V DOWN.

Design files at: https://github.com/microresearch/allcolours/SR_segments

Cheatsheet with manual cards: https://1010.co.uk/

With thanks to Melissa Aguilar for poster/manual layout and design.

caput draconis is released under the GPL GNU General Public License.

** basic blurb description: 

Caput draconis (CD) is the latest ourorack (ouroboric) module for
gnarlular processing, and advanced cross frequency CV and audio
pattern generation, encoding a series of successively pleasurable and
tortuous sliding dislocations

Intended as lonely serpent's head or as companion for All the Colours
of the Noise extends in four directions the ouroboric becoming-noise
of the contemporary eurorack rosarium.

Four draconic heavily simulated shift registers are enchained, interlocked, woven and
segmented, recursively feeding on each other in turn, vomiting noise
and wormy symphonies according to moon phases and shifting nodal
paths. It is to have done with the judgement of god/s.

CD can be considered as 64^4 different instruments depending on modal
configuration informed by lunar phases and astrogeomantic time signatures. 

emphasise that it is about the creation of more than 16777216 unique
instruments through manipulation of modes and parameters

towards a synthesis without modules...

successive pleasurable and tortuous dislocations 

Caput draconis (CD) is/will be the latest ourorack ... companion
extending the ouroboric becoming-noise of the contemporary eurorack
rosarium


//Successive Slidings of Pleasure (French: Glissements progressifs du plaisir) RG

extends the pulse driven shift register schemes of All
Colours with 4 and more interlocking shift registers or "runglers"
(each with 64 modes of operation) running at all different speeds. The
emphasis is on complex CV generation and processing of analogue
signals, as well as clock and pulse outputs. Release date March 2023.

[All the Colours of the Noise is a new rosarium of eurorack module for
ouroboric becoming-noise at all timescales and frequencies, from the
cloudy smoke of stray industrial furnace noise burning snakes to
thunder and lightning noise from stricken server farms.]


Closer to caput draconis as the crescent moon moves into the northern ecliptic hemisphere at 18.56 GMT this evening. 

Successive pleasurable and tortuous dislocations 

we also had:

By degrees the idea of cultivation subsided into that of merely
pastoral care. This slowly became merged in a sense of retirement —
this again in a consciousness of solitude.

[E. A. Poe. The Domain of Arnheim.]

module for one bit landscape gardening...


** design/inspirations POSTER

cover as card image in colour - cover/back + 6 sides with poster - cover and back head and tail! scan

in no specific order A5:

1 - blurb and credits: Poe quote, description

Credits/info: 

For Rob Hordijk and all shifting registers.

Technical and HOWTO
20HP, 150mA at +12V, 30mA at -12V, 0mA at 5v. Multiple CV inputs and audio outputs. Power is red stripe/-12V DOWN.

Design files at: https://github.com/microresearch/allcolours

Cheatsheet with manual cards: https://1010.co.uk/AlltheColours_extendedmanual.pdf

With thanks to Melissa Aguilar for poster/manual layout and design.

All the Colours... is released under the GPL GNU General Public License.


2 - panel layout
3 - general desc/theory
4 - theory of operation
5 - hints and tips /working with AC
6 - glossary


poster [could also be booklet for TOAD/andy later]

how to image/notate panel - that the description and panel/images are themselves subjected to shift reg (eg. each pixel line of panel image - try this!)

** 8/3/2023

- less cycle on NN and RR, make plain in manual how we use these

** 5/3/2023

- table for modes:

-  | function | x | y - what they do... /// x4 for each side - and similar blocks shaded or coloured... spreadsheet?
1  |
64 |

function is what is the bit and how does it enter? can also effect shifting (types of shift - what these are) and other SRs

make clear that previous settings affect future modes and that there is a complete reset

** 28/2/2023

theory of operation:

generic: 4 interlocked (software) shift registers, with configurable
routing, speed and length. each has CV control, an adjustable mode,
and clock inputs. Some have pulse inputs. All is bits, 1s and 0s but
analogue signals can be input and can be generated using combinations
of these bits.

hardware in detail:

Each side has 3 knobs and 2 CV inputs, and a clock input. The left and
right sides have a pulse input. The central knob on each side controls
the mode for that SR, the first knob (left to right, up to down) is X,
the third is Y. In the first 32 modes on each side, and other modes
depending on mode, the X control (CV and knob) controls speed. In
modes 33-48 speed is set by the clock input. The clock input is normed
to an artificial, internally generated clock signal. Of course,
inserting a cable here, dissolves this connection. Left and right SRs
both have a pulse input which is simply XORed into the SR; it can be
use to mix new signals into each SR. Left, right and lower SRs each
have two different pulse outputs directly from their own SR bits.

The top SR has an audio input, the bottom SR has an audio
output. Different input and output encodings can be chosen using the
first mode [0] in the case of top and bottom SRs. In some cases on
mode 0 for the top, audio entry SR, internal signals are generated
(noise, oscillation). In the case where no audio signal is plugged in
physically, the output signal from the 2nd output SR is normed to the
input for feedback. Note that feedback can wail or die!

serpent as blackbox:

Each of the four SRs has internally length, speed, incoming route,
function and type of interlock with incoming SRs. Speed can be set and
manipulated by the X (CV/knob) parameter, output from other SRs
(feedback and rungling), or by the clock input depending one of 64
different modes.

Length, route, interlock and function are also set and configured
within the modes. Moving quickly across modes does not result in
setting intermediate values. Length is the length of each segment
(1-32), route specifies the incoming routes (these can be multiple)
from other SRs, function is the mode of operation (eg. is it allowed
to cycle, or the fix the probability of an incoming bit), and
interlock is how it deals with incoming SRs which are faster or slower
than itself. These can be imagined as churning, interlocking wheels.

Modes in general are grouped as to functions dealing with route,
function and so on. The first 16 modes on each side are basic in
control, with the first [0. far left] mode always as a default reset
and a simple route in, with configuration of incoming/outgoing signal
codec (top, bottom) or of length (left, right) on the Y knob/CV. The
next 16 modes are more tricky, then we have the 16 strobe modes and
finally, except on the right side, there are 16 recursive modes which
fold back parameters onto each other under CV control. These can be
reset in the last (far right) mode setting. Modes are mostly aligned
across all SRs.

On the last 16 modes of the right side, there are the global modes
which affect global order of execution (which SR runs after which, not
the same as route) routing and recursive parameters. These are reset
in the final (far right turn) mode which also sets and can reset the
global route using the Y parameter. The default route is from top to
left to bottom to right (and back to top if allowed). But each SR can
control its own route in some modes, and can choose when and if it
allows bits in. // 0 mode on RR also resets all

Input and output settings

what else to add? tails, 

Glossary:

[Glossary: SeRpent - shift register]

describe SR as a function 

SR can be described as a serpentine function which eats bits, passes
each bit at clock speed along all its segments, and then excretes that
bit - either to feed on it in a delayed ouroboric cycle or to pass
this bit to another register. It is a form or wormy memory.

Rungler: 

The creation of Rob Hordijk, a rungler is a shift register clocked by
one oscillator and receiving its data input from the other
oscillator. In the recursive cases of CD, the oscillators are any abstract
function or input which can be implemented by an SR.

** 24/2/2023

announce moon node at 19.58!

As the crescent ...

images: new panelSr, inspired alch, moon diagram, geomantic

- image trial for panel - use forhyyt python to pass through 1-4 SRs (in test.c?)

with add functions but do basic test:

image -> string

C or python code manipulates string...

string -> image (and colour)

[- thinking that manual could be A3 riso (but then folded?) poster... or set of cards like AC (for all?)]

** 23/2/2023

notebook notes:

moon nodes and diagrams, connection to geomancy, ascii thurneysser

ascend/descend, digital moon

layout diagram of connected segments, show that can be shifting like turing reader drawings (and to do own reader)

layers - speed, route, prob, types

each side has...

modes...

** 20/2/2023

tips:

- such as use of pulse ins if sections start to run out, also to mix in signals...
- take out clock ins if not being used for strobe speeds or pulses
- operate right hand side at slower speeds or use slow pulsing clock in // not always

work from bottom up - useful configuration on bottom, leave it and start work from top

the user shoots
the user kills

how to patch following geomantic instructions

** 9/2/2023

- how interacts with AC to fill in from notes:

- use of HF clock signals as strobe clock for CD
- use of comped noise as strobe and as noise/snare entry 
- feedback path with AC
- pulses from CD -> ?
- AC as audio source
- use of comparator for clocks

hints and tips also: feedback of pulses, what to do when it runs out

use of globals - order of playing

how to play it - consider the combinations of the 4 modes/nodes as an
instrument itself determined by the collision of modes and the moon's
phases.

** new 4/5/2022+

- how to use with geomantic layout of 4 figures...

[from segmodes]
head fire C 1=one dot/active. 0=2 dots/passive. 
neck air L
body water N
feet earth R

each figure has active/passive lines (passive as static) for 4 layers - in the 4 elements

so then one card would give how to operate (eg. which to leave static) but then for 4 cards?

- grid of features with symbols eg.

      clk spd 
xmode  *   -

eg. does it use clk (as param, as timing/speed, as pulse)

what else??? fill in

also like grid from moods modes/

** Heavens material

https://academic.oup.com/jcmc/article/3/3/JCMC334/4584381

vehicle

 A walk-in can be defined as "an entity who occupies a body that has been vacated by its original soul"

next level

** or caput draconis materials

geomancy figures 

** ascii art/outputs for different SR varieties

** artful description/older

Heavens\ extends the pulse driven shift register schemes of All
Colours with 4 and more interlocking shift registers or "runglers"
(each with 64 modes of operation) running at all different speeds. The
emphasis is on complex CV generation and processing of analogue
signals, as well as clock and pulse outputs. Release date March 2023.

** basic older description

how we call SR: as rungler, as a walk-in

Heavens\ presents four interlocking or overlapping shift registers, runglers or digital walk-ins.

Each register has a speed, a mode (of 64) and a length (up to 32 cells) which
can be varied in most cases by control voltage (CV), or by other
parameters. Each has a clock pulse input which, depending on mode
determines speed of the register or some other parameter, such as a
freeze or a strobe.

Each register has 64 modes which can only be selected by the mode
knob. There are 3 major modes which choose how the speed of the
register is determined: by speed CV, by speed CV and another shift
register, or by incoming clock pulses.

The top register is for incoming signals, such as the analogue input
or internal digital noise. Here the mode largely determines the type
of input and how it is processed (eg. how many bits).

The lowest register is for outgoing CV and audio rate signals which
are converted from the digital registers according to various schemes
set by the mode (eg. how many bits).

The left and right registers are used to delay, process and feed back
between top and bottom. The routing of the four distinct registers is
largely fixed as follows (again a few modes can change this fixed
routing). Top register feeds into left which feeds into both lower and
right. The right feeds back in to the top. 

Left and right registers have additional pulse in inputs and two pulse
outs. One of these is half the speed of the other/one division. The
lower register also has two pulses outs giving a total of six pulse
outputs and one analaogue CV/audio out.

All registers can run at differing speeds, the slowest speed is a full
stop which does not advance the register. If a register is running
faster than it's feed-in register it will cycle through a frozen copy
of that register (a ghost) which is updated as soon as the feed-in
runs again. This means that a stopped register will merely repeat its
contents feeding another faster or unstopped register. Some registers
further manipulate their own incoming ghost registers.

** modes drawn out - how we notate these eg. symbols for probabilty, how we make a grid?

** layout and panel scan

** other params/ power etc.

20HP, XmA at +12V, XmA at -12V, 0mA at 5v. Multiple inputs, single audio/CV outputs, multiple pulse outputs. Power is red stripe/-12V DOWN.

** any example patches

** links/reading list/reader

- other random
- http://www.ccru.net/digithype/Afrobinary.htm
- https://monoskop.org/images/f/f1/CCRU_Abstract_Culture_Digital_Hyperstition_1999.pdf

geomancy

shift registers

lunar nodes and alignments
