* MODER

RSR: 

- feedback/probability
- independent DAC functions/generators (abstract, some in)
- other functions (more of RSR etc. eg. global routings, drop all routes, sync) - special modes with/without feedthrough

R- set of global routes eg. cut all routes on strobe, sync routes, bump routes etc.

- that can GSHIFT itself as a 0 always to prevent binroutes into others (but does this effect anything)

*TODO: sync modes*

** older

// right hand functions

//DONE//checked for pulsoutsX, pulsins and strobey

/*

latest:

CV:
0-15 - basic routes and probabilities
15-31 detached

CVDAC:
32-47

INTMODES:
cv as routings, probabilities etc.
and global set routes, set which dacs is dac for adc, set fake clkins




CVmodes: basics, prob modes entry/loopback, esoteric modes, << bumps, route from DAC, prob from DAC

DACmodes: basics, esoterics

INTmodes: route from CV, prob from CV, others? + change global routes, fake clks, use as DAC, entry of adc/non-adc bits from top

above, different kinds of DAC out

*/


// CV modes


